version: '3'
services:
  vuetify:
    image: emanagerui:1.0
    build:
      context: ./Vuetify
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "3000:3000"
  file_server:
    image: emanagerfs:1.0
    build:
      context: ./FileServer
      dockerfile: Dockerfile
    container_name: file_server
    ports:
      - "4000:4000"
    volumes:
      - C:\Users\Sergi\ComsaUI\Vuetify\IOTDevices:/FileServer/data
